2022-06-06 23:13:22,013 INFO    MainThread:27201 [wandb_setup.py:_flush():75] Loading settings from /home/j-zhong/.config/wandb/settings
2022-06-06 23:13:22,013 INFO    MainThread:27201 [wandb_setup.py:_flush():75] Loading settings from /home/j-zhong/work_place/Bi-Level-Actor-Critic-with-F/wandb/settings
2022-06-06 23:13:22,013 INFO    MainThread:27201 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-06-06 23:13:22,013 INFO    MainThread:27201 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'trainer.py', 'program': '/home/j-zhong/work_place/Bi-Level-Actor-Critic-with-F/trainer.py'}
2022-06-06 23:13:22,014 INFO    MainThread:27201 [wandb_init.py:_log_setup():386] Logging user logs to /home/j-zhong/work_place/Bi-Level-Actor-Critic-with-F/wandb/run-20220606_231322-2at8hzud/logs/debug.log
2022-06-06 23:13:22,014 INFO    MainThread:27201 [wandb_init.py:_log_setup():387] Logging internal logs to /home/j-zhong/work_place/Bi-Level-Actor-Critic-with-F/wandb/run-20220606_231322-2at8hzud/logs/debug-internal.log
2022-06-06 23:13:22,014 INFO    MainThread:27201 [wandb_init.py:init():420] calling init triggers
2022-06-06 23:13:22,014 INFO    MainThread:27201 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-06-06 23:13:22,014 INFO    MainThread:27201 [wandb_init.py:init():471] starting backend
2022-06-06 23:13:22,014 INFO    MainThread:27201 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-06-06 23:13:22,034 INFO    MainThread:27201 [backend.py:ensure_launched():219] starting backend process...
2022-06-06 23:13:22,048 INFO    MainThread:27201 [backend.py:ensure_launched():224] started backend process with pid: 27278
2022-06-06 23:13:22,053 INFO    MainThread:27201 [wandb_init.py:init():480] backend started and connected
2022-06-06 23:13:22,058 INFO    MainThread:27201 [wandb_init.py:init():550] updated telemetry
2022-06-06 23:13:22,083 INFO    MainThread:27201 [wandb_init.py:init():581] communicating current version
2022-06-06 23:13:24,464 INFO    MainThread:27201 [wandb_init.py:init():586] got version response upgrade_message: "wandb version 0.12.17 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-06-06 23:13:24,465 INFO    MainThread:27201 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-06-06 23:13:54,467 INFO    MainThread:27201 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-06-06 23:13:54,468 ERROR   MainThread:27201 [wandb_init.py:init():601] backend process timed out
2022-06-06 23:13:54,468 ERROR   MainThread:27201 [wandb_init.py:init():610] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-06-06 23:13:54,521 ERROR   MainThread:27201 [wandb_init.py:init():978] error
Traceback (most recent call last):
  File "/home/j-zhong/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 951, in init
    run = wi.init()
  File "/home/j-zhong/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 614, in init
    backend.cleanup()
  File "/home/j-zhong/anaconda3/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 248, in cleanup
    self.interface.join()
  File "/home/j-zhong/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/home/j-zhong/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/home/j-zhong/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/j-zhong/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/j-zhong/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
